version: '3'

services:
  django:
    build: .
    restart: always
    ports:
      - '8000:8000'
    environment:
      POSTGRES_DB: 'online_shop_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: db
      POSTGRES_PORT: '5432'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'online_shop_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  postgres_data: