version: '3'

services:
  django:
    build: .
    ports:
      - '8000:8000'
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'online_shop_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'