# Generated by Django 3.2.16 on 2023-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='количество товара в корзине')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'корзина товара',
                'verbose_name_plural': 'корзина товаров',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='номер заказа')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий к заказу')),
                ('status', models.SmallIntegerField(choices=[(1, 'создан'), (2, 'подтвержден'), (3, 'отклонен')], default=1)),
                ('basket_history', models.JSONField(default=dict, verbose_name='история корзины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата формирования заказа')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='дата отклонения')),
                ('comment_for_reject', models.TextField(default='Уточняется', verbose_name='комментарий при отклонении')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created_at',),
            },
        ),
    ]
