# Generated by Django 3.2.16 on 2023-03-17 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_confirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_confirm', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил админ'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_reject', to=settings.AUTH_USER_MODEL, verbose_name='отклонил админ'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='владелец заказа'),
        ),
        migrations.AddField(
            model_name='basket',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.item', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='корзина для пользователя'),
        ),
    ]
