# Generated by Django 3.2.16 on 2023-03-17 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_confirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_confirm', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил админ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_reject', to=settings.AUTH_USER_MODEL, verbose_name='отклонил админ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата отклонения'),
        ),
    ]
