# Generated by Django 3.2.16 on 2023-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment_for_reject',
            field=models.TextField(default='Уточняется', verbose_name='комментарий при отклонении'),
        ),
    ]
